# Site settings
title: Meu blog pessoal
email:liviafariacarvalho@gmail.com
url: https://liviafariacarvalho.github.io/
description: Bem vindo ao meu blog pessoal! Meu nome é Lívia, tenho 19 anos e faço licenciatura em matemática na UFV de Florestal.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000001'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  
    
  - title: facebook
    url: https://www.facebook.com/livia.faria.9256
  - title: Instagram
    url: https://www.instagram.com/livia_cfaria/
  - title: github
    url: https://github.com/liviafariacarvalho
# Build settings
markdown: kramdown
permalink: pretty
